### ISSUE TITLE
Segfault __memcpy_sse2_unaligned on Throwable.toString()

### ISSUE THREAD

**Issue by dlangBugzillaToGithub** [dlang/dmd#17314]
### CC List

* Ludovit Lucenic

### Description

````markdown
I receive a segfault in my program when I am trying to print out information on Throwable instance in a catch block.

The GDB backtrace:

Program received signal SIGSEGV, Segmentation fault.
__memcpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:35
35	../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S: Adresár alebo súbor neexistuje.
(gdb) bt full
#0  __memcpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:35
No locals.
#1  0x0000000000c2880f in _d_arraysetlengthiT ()
No symbol table info available.
#2  0x0000000000c70cf9 in core.demangle.Demangle.__T10doDemangleS48_D4core8demangle8Demangle16parseMangledNameMFmZvZ.doDemangle() ()
No symbol table info available.
#3  0x0000000000c1fbb0 in core.runtime.defaultTraceHandler() ()
No symbol table info available.
#4  0x0000000000c1f94b in core.runtime.defaultTraceHandler() ()
No symbol table info available.
#5  0x0000000000c1f85c in core.runtime.defaultTraceHandler() ()
No symbol table info available.
#6  0x0000000000c1e403 in object.Throwable.toString() ()
No symbol table info available.
#7  0x0000000000c1e298 in object.Throwable.toString() ()
No symbol table info available.
#8  0x0000000000a5d483 in les.ast.CommandCall.eval() (this=0x7ffff3734330) at src/les/ast.d:988
No locals.
...

The code 'src/les/ast.d' where the exception is caught and printed is (line 988, code 't.toString()') here:

981	try {
982		return runBuiltInCommand(execEnv, dCode, parameterTree);
983	}
984	catch (Throwable t) {
985		execEnv.context.callLocation.srcCode = STRING_EMPTY;
986		debug (echoToConsole) logError("EXCEPTION %s THROWN in BIC %s in method: %s
%s",
987		  t.classinfo.name, bicName[getBicNamePrefix().length+1..$],
988 >>>		  execEnv.context, t.toString().indent().chomp());
989    		execEnv.requestLog.logError("EXCEPTION %s THROWN in BIC %s in method: %s
%s",
990		  t.classinfo.name, bicName[getBicNamePrefix().length+1..$],
991		  execEnv.context.toString!true(), t.toString().indent().chomp());
992	}

-----
The system is Debian Wheezy, 64bit.
ldd (Debian GLIBC 2.19-18) 2.19
DMD64 v2.068.2
----
What more information is needed?
````

**Comment by dlangBugzillaToGithub** [comment]
#### llucenic commented on 2015-10-13T22:29:05Z



````markdown
The expected toString() output is following:

-----
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989] EXCEPTION std.file.FileException THROWN in BIC file.loadTree in method: /sync/server.process() on Ln 279, Col 15: [Synchronizačný server]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	std.file.FileException@std/file.d(207): /data/projekt/arinas/home/direct/example/project.sjp.MAIN.repo: No such file or directory
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	----------------
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(@trusted void[] std.file.read(const(char[]), ulong)+0xa5) [0xb0e6f9]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(@safe immutable(char)[] std.file.readText!(immutable(char)[]).readText(const(char[]))+0x24) [0x8e4814]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(arinas.internal.tree.LaexTree arinas.platform.builtin.file.loadTree.exec(arinas.platform.runtime.env.ExecEnv, arinas.internal.tree.LaexTree)+0x69) [0x8cd369]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(arinas.internal.tree.LaexTree les.ast.CommandCall.runBuiltInCommand(arinas.platform.runtime.env.ExecEnv, arinas.platform.builtin.BuiltInCommand, arinas.internal.tree.LaexTree[])+0xec) [0x93609c]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(arinas.internal.tree.LaexTree les.ast.CommandCall.eval(arinas.platform.runtime.env.ExecEnv)+0x4ce) [0x935ca6]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(void les.ast.CommandAssignRight.applyOp(arinas.platform.runtime.env.ExecEnv, les.ast.CommandBlock)+0x86) [0x934356]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(void les.ast.CommandTreeRight.runCommand(arinas.platform.runtime.env.ExecEnv)+0x21b) [0x934173]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(void les.ast.Command.run(arinas.platform.runtime.env.ExecEnv)+0xdc) [0x932e2c]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(void les.ast.CommandTreeEval.runCommand(arinas.platform.runtime.env.ExecEnv)+0x107) [0x933bc7]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(void les.ast.Command.run(arinas.platform.runtime.env.ExecEnv)+0xdc) [0x932e2c]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(void les.ast.CommandSequence.runCommand(arinas.platform.runtime.env.ExecEnv)+0xb4) [0x93325c]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(void les.ast.CommandBlock.runCommand(arinas.platform.runtime.env.ExecEnv)+0x207) [0x93382f]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(void les.ast.Command.run(arinas.platform.runtime.env.ExecEnv)+0xdc) [0x932e2c]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(void les.ast.CommandTreeRight.runCommand(arinas.platform.runtime.env.ExecEnv)+0x1f7) [0x93414f]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(void les.ast.Command.run(arinas.platform.runtime.env.ExecEnv)+0xdc) [0x932e2c]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(void les.ast.CommandTreeEval.runCommand(arinas.platform.runtime.env.ExecEnv)+0x107) [0x933bc7]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(void les.ast.Command.run(arinas.platform.runtime.env.ExecEnv)+0xdc) [0x932e2c]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(void les.ast.CommandSequence.runCommand(arinas.platform.runtime.env.ExecEnv)+0xb4) [0x93325c]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(void les.ast.DefaultClause.runCommand(arinas.platform.runtime.env.ExecEnv)+0x61) [0x935191]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(void les.ast.Command.run(arinas.platform.runtime.env.ExecEnv)+0xdc) [0x932e2c]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(void les.ast.CommandSwitch.runCommand(arinas.platform.runtime.env.ExecEnv)+0xdf) [0x934f4f]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(void les.ast.Command.run(arinas.platform.runtime.env.ExecEnv)+0xdc) [0x932e2c]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(void les.ast.CommandSequence.runCommand(arinas.platform.runtime.env.ExecEnv)+0xb4) [0x93325c]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(void les.ast.Method.runCommand(arinas.platform.runtime.env.ExecEnv)+0x101) [0x933471]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(void les.ast.Command.run(arinas.platform.runtime.env.ExecEnv)+0xdc) [0x932e2c]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(arinas.internal.tree.LaexTree arinas.platform.runtime.operation.LesOperation.run(arinas.platform.runtime.env.ExecEnv)+0x15d) [0x92900d]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(arinas.internal.tree.LaexTree arinas.platform.runtime.execute.Executor.execute(arinas.platform.runtime.env.ExecEnv, arinas.internal.tree.LaexTree, immutable(char)[], arinas.internal.tree.LaexTree)+0x7fe) [0x9275fe]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(arinas.internal.tree.LaexTree les.ast.CommandRun.eval(arinas.platform.runtime.env.ExecEnv)+0x4a8) [0x936ec0]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(void les.ast.CommandAssignRight.applyOp(arinas.platform.runtime.env.ExecEnv, les.ast.CommandBlock)+0x86) [0x934356]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(void les.ast.CommandTreeRight.runCommand(arinas.platform.runtime.env.ExecEnv)+0x21b) [0x934173]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(void les.ast.Command.run(arinas.platform.runtime.env.ExecEnv)+0xdc) [0x932e2c]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(void les.ast.CommandTreeEval.runCommand(arinas.platform.runtime.env.ExecEnv)+0x107) [0x933bc7]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(void les.ast.Command.run(arinas.platform.runtime.env.ExecEnv)+0xdc) [0x932e2c]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(void les.ast.CommandSequence.runCommand(arinas.platform.runtime.env.ExecEnv)+0xb4) [0x93325c]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(void les.ast.CommandBlock.runCommand(arinas.platform.runtime.env.ExecEnv)+0x207) [0x93382f]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(void les.ast.CommandBlock.runAssign(arinas.platform.runtime.env.ExecEnv)+0x63) [0x93396b]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(void les.ast.CommandTreeBlock.runCommand(arinas.platform.runtime.env.ExecEnv)+0xce) [0x933cfe]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(void les.ast.Command.run(arinas.platform.runtime.env.ExecEnv)+0xdc) [0x932e2c]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(void les.ast.CommandIf.runCommand(arinas.platform.runtime.env.ExecEnv)+0x92) [0x93495a]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(void les.ast.Command.run(arinas.platform.runtime.env.ExecEnv)+0xdc) [0x932e2c]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(void les.ast.CommandSequence.runCommand(arinas.platform.runtime.env.ExecEnv)+0xb4) [0x93325c]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(void les.ast.Method.runCommand(arinas.platform.runtime.env.ExecEnv)+0x101) [0x933471]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(void les.ast.Command.run(arinas.platform.runtime.env.ExecEnv)+0xdc) [0x932e2c]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(arinas.internal.tree.LaexTree arinas.platform.runtime.operation.LesOperation.run(arinas.platform.runtime.env.ExecEnv)+0x15d) [0x92900d]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(arinas.internal.tree.LaexTree arinas.platform.runtime.execute.Executor.execute(arinas.platform.runtime.env.ExecEnv, arinas.internal.tree.LaexTree, immutable(char)[], arinas.internal.tree.LaexTree)+0x7fe) [0x9275fe]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(arinas.internal.tree.LaexTree les.ast.CommandRun.eval(arinas.platform.runtime.env.ExecEnv)+0x4a8) [0x936ec0]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(void les.ast.CommandAssignRight.applyOp(arinas.platform.runtime.env.ExecEnv, les.ast.CommandBlock)+0x86) [0x934356]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(void les.ast.CommandTreeRight.runCommand(arinas.platform.runtime.env.ExecEnv)+0x21b) [0x934173]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(void les.ast.Command.run(arinas.platform.runtime.env.ExecEnv)+0xdc) [0x932e2c]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(void les.ast.CommandTreeEval.runCommand(arinas.platform.runtime.env.ExecEnv)+0x107) [0x933bc7]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(void les.ast.Command.run(arinas.platform.runtime.env.ExecEnv)+0xdc) [0x932e2c]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(void les.ast.CommandSequence.runCommand(arinas.platform.runtime.env.ExecEnv)+0xb4) [0x93325c]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(void les.ast.Method.runCommand(arinas.platform.runtime.env.ExecEnv)+0x101) [0x933471]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(void les.ast.Command.run(arinas.platform.runtime.env.ExecEnv)+0xdc) [0x932e2c]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(arinas.internal.tree.LaexTree arinas.platform.runtime.operation.LesOperation.run(arinas.platform.runtime.env.ExecEnv)+0x15d) [0x92900d]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(arinas.internal.tree.LaexTree arinas.platform.runtime.execute.Executor.execute(arinas.platform.runtime.env.ExecEnv, arinas.internal.tree.LaexTree, immutable(char)[], arinas.internal.tree.LaexTree)+0x7fe) [0x9275fe]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(void arinas.platform.web.handler.direct(vibe.http.server.HTTPServerRequest, vibe.http.server.HTTPServerResponse)+0x454) [0x92abec]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(void std.functional.DelegateFaker!(void function(vibe.http.server.HTTPServerRequest, vibe.http.server.HTTPServerResponse)*).DelegateFaker.doIt(vibe.http.server.HTTPServerRequest, vibe.http.server.HTTPServerResponse)+0x60) [0xa8daac]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(_D4vibe4http6router9URLRouter13handleRequestMFC4vibe4http6server17HTTPServerRequestC4vibe4http6server18HTTPServerResponseZ21__T9__lambda3TmTAAyaZ9__lambda3MFmMAAyaZv+0x1bc) [0xa50138]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(const(void function(immutable(char)[], scope void delegate(ulong, scope immutable(char)[][]))) vibe.http.router.MatchTree!(vibe.http.router.Route).MatchTree.doMatch+0x185) [0xa50d85]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(void vibe.http.router.MatchTree!(vibe.http.router.Route).MatchTree.match(immutable(char)[], scope void delegate(ulong, scope immutable(char)[][]))+0x93) [0xa50653]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(void vibe.http.router.URLRouter.handleRequest(vibe.http.server.HTTPServerRequest, vibe.http.server.HTTPServerResponse)+0x13c) [0xa4ff20]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(_D4vibe4http6router9URLRouter13handleRequestMFC4vibe4http6server17HTTPServerRequestC4vibe4http6server18HTTPServerResponseZ21__T9__lambda3TmTAAyaZ9__lambda3MFmMAAyaZv+0x1bc) [0xa50138]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(const(void function(immutable(char)[], scope void delegate(ulong, scope immutable(char)[][]))) vibe.http.router.MatchTree!(vibe.http.router.Route).MatchTree.doMatch+0x185) [0xa50d85]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(void vibe.http.router.MatchTree!(vibe.http.router.Route).MatchTree.match(immutable(char)[], scope void delegate(ulong, scope immutable(char)[][]))+0x93) [0xa50653]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(void vibe.http.router.URLRouter.handleRequest(vibe.http.server.HTTPServerRequest, vibe.http.server.HTTPServerResponse)+0x13c) [0xa4ff20]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(bool vibe.http.server.handleRequest(vibe.core.stream.Stream, vibe.core.net.TCPConnection, vibe.http.server.HTTPListenInfo, ref vibe.http.server.HTTPServerSettings, ref bool)+0x1719) [0xaa1979]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(void vibe.http.server.handleHTTPConnection(vibe.core.net.TCPConnection, vibe.http.server.HTTPListenInfo)+0x197) [0xaa0167]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(void vibe.http.server.listenHTTPPlain(vibe.http.server.HTTPServerSettings).doListen(vibe.http.server.HTTPListenInfo, bool).__lambda3(vibe.core.net.TCPConnection)+0x2e) [0xa9fbce]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(void vibe.core.drivers.libevent2_tcp.ClientTask.execute()+0x47f) [0xa922cf]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(void vibe.core.core.makeTaskFuncInfo!(void delegate()).makeTaskFuncInfo(ref void delegate()).callDelegate(vibe.core.core.TaskFuncInfo*)+0x6e) [0xa0f722]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(void vibe.core.core.CoreTask.run()+0xd4) [0xa0d908]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(void core.thread.Fiber.run()+0x2a) [0xb386ea]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	/data/work/space/eclipse/arinas/platform/bin/ars-platform(fiber_entryPoint+0x61) [0xb385d9]
	[3AA26F61:36760361 23:31:16.6138300]  RUNTIME ERROR [les.ast.CommandCall.eval:989]    	[(nil)]
-----
````
