### ISSUE TITLE
Test Suite: C++ interop tests heisenbug

### ISSUE THREAD

**Issue by dlangBugzillaToGithub** [dlang/dmd#19755]
### CC List

* Mathias LANG (@Geod24)

### Description

````markdown
C++ interop tests / Run (macOS-10.15, clang-5.0.2)
failed 4 minutes ago in 6m 4s

The log file:
------------------------------------
Post [Posix] Load cached clang54s

Post job cleanup.
/usr/bin/tar -cz -f /Users/runner/work/_temp/557fd234-fb17-4d35-a698-3480564cb452/cache.tgz -C /Users/runner/work/dmd/dmd/clang+llvm-5.0.2-x86_64-apple-darwin .
[warning]Cache service responded with 503 during chunk upload.
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: EBADF: bad file descriptor, read
Emitted 'error' event on ReadStream instance at:
    at internal/fs/streams.js:167:12
    at FSReqCallback.wrapper [as oncomplete] (fs.js:470:5) {
  errno: -9,
  code: 'EBADF',
  syscall: 'read'
}
````

**Comment by dlangBugzillaToGithub** [comment]
#### pro.mathias.lang (@Geod24) commented on 2020-07-30T08:32:33Z



````markdown
That's a spurious failure due to a network error. This post-job cleanup is automatic so there's nothing we can do about it. If you can isolate a cause, please report it to the upstream project (https://github.com/actions/cache).
````

**Comment by dlangBugzillaToGithub** [comment]
#### bugzilla (@WalterBright) commented on 2020-11-24T11:34:15Z



````markdown
I'm not suggesting fixing the cause, I realize it is not under our control. What I suggest is for these sorts of errors, have that test case automatically retried after sleeping for a minute or so.

If it keeps failing after multiple tries, then stop.
````
